package negotiator.actions;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;


import negotiator.AgentID;
/**
 * An Action generated by the Negotiation Session to inform the agent of the turn ending.
 * The AgentID in such action will always be null.
 * If the agent was inactive in the last turn, the flag wasInactive is set.
 * 
 * @author Yinon Oshrat
 */
@XmlRootElement
public class EndTurn extends Action {
	private int turn;
	
	private Boolean wasInactive = null;
	
	public EndTurn() {}
	/** 
	 * Creates a new instance of EndTurn
     * @param turn - the turn that begins now.
     */
    public EndTurn(int turn) {
        super(null);
        this.turn=turn;
    }
   
    /**
     * @return the number of the new turn that now begins
     */
    @XmlElement
    public int getTurn() {
    	return turn;
    }
    
	public String toString() {
        return "(EndTurn: turn " + turn + ", wasInactive " + wasInactive + " )";
    }    
	
	public void setWasInactive(Boolean wasInactive) {
		this.wasInactive = wasInactive;
	}
	
    /**
     * @return true is the receiving agent was inactive in the last turn.
     */
    @XmlElement 
    public Boolean getWasInactive() {
		return wasInactive;
	}
    
	public Object clone() throws CloneNotSupportedException {
		EndTurn result = (EndTurn)super.clone();
		result.turn = turn;
		result.wasInactive = wasInactive;
		return result;
	}
}
