/*
 * SessionFrame.java
 *
 * Created on November 17, 2006, 3:46 PM
 */

package negotiator.gui;

import java.util.Vector;
import javax.swing.table.AbstractTableModel;

import negotiator.NegotiationOutcome;
import javax.swing.JFrame;

/**
 *
 * @author  dmytro
 */
@SuppressWarnings("serial")
public class SessionFrame extends JFrame {
	SessionOutcomesTableModel model;
	/** Creates new form SessionFrame */
	public SessionFrame(String agentAName, String agentBName) {
		super();
		initComponents();
		model = new SessionOutcomesTableModel(agentAName, agentBName);
		tableSessionOutcomes.setModel(model);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
	private void initComponents() {
		jScrollPane1 = new javax.swing.JScrollPane();
		tableSessionOutcomes = new javax.swing.JTable();

		getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Negotiation results");
		tableSessionOutcomes.setModel(new javax.swing.table.DefaultTableModel(
				new Object [][] {
						{null, null, null, null},
						{null, null, null, null},
						{null, null, null, null},
						{null, null, null, null}
				},
				new String [] {
						"Title 1", "Title 2", "Title 3", "Title 4"
				}
		));
		jScrollPane1.setViewportView(tableSessionOutcomes);

		getContentPane().add(jScrollPane1);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	public void addNegotiationOutcome(NegotiationOutcome no) {
		if(no!=null) model.addNegotiationOutcome(no);
	}
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tableSessionOutcomes;
	// End of variables declaration//GEN-END:variables

	class SessionOutcomesTableModel extends AbstractTableModel {
		private Vector sessionOutcomes;
		//        private NegotiationTemplate nt;
		private String agentAName;
		private String agentBName;
		public SessionOutcomesTableModel (String agentAName, String agentBName)  {
			this.agentAName = agentAName;
			this.agentBName = agentBName;
			sessionOutcomes = new Vector();
		}
		public int getColumnCount() {return 4;}

		public int getRowCount() {return sessionOutcomes.size();}

		public String getColumnName(int col) {
			String name;
			switch(col) {
			case 0: name = "Session #";break;
			case 1: name ="Utility for "+agentAName;break;
			case 2: name ="Utility for "+ agentBName;break;
			case 3: name ="Protocol ErrorRemarks";break;
			default: name = "";
			}
			return name;
		}
		public Class getColumnClass(int c) {return (new String()).getClass();}        

		public Object getValueAt(int row, int col) {
			Object value = null;
			NegotiationOutcome nt = (NegotiationOutcome)(sessionOutcomes.get(row));
			switch(col) {
			case 0: value = nt.sessionNumber;break;
			case 1: value = nt.agentAutility;break;
			case 2: value = nt.agentButility;break;
			case 3: value = nt.ErrorRemarks;break;
			default:value ="";
			}
			return value;
		}
		public void addNegotiationOutcome( NegotiationOutcome no) {
			sessionOutcomes.add(no);
			fireTableDataChanged();
		}
	}



	/**
	 * demo program
	 */
	public static void main(String[] args) {
		JFrame frame = new SessionFrame("agentA", "agentB");
		frame.setVisible(true);
	}
}
